# Site settings
title: Shakya Mirror # site title
description:
  >- # site description  # Follows a logical and philosophical progression: cognition → spirit → existence | A reflective guide to truth, presence, and self-awareness — through mind, soul, and the illusions of life. A space for introspection, clarity, and timeless truth — through the mirror of awareness.
  A reflective journey through mind, soul, and life — to awaken what is already whole.
lang: en-US # default lang
timezone: Asia/Kolkata # set your timezone
image: assets/img/og-image-vagabond.webp # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/harendra-shakya/harendra-shakya.github.io # site repo [optional]
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: Harendra Shakya # author name
  bio: >- # tell to the world
    Preoccupied with a single leaf, you won't see the tree. Preoccupied with a single tree, you'll miss the entire forest.
  username: harendra-shakya # general username
  github: harendra-shakya # github username
  twitter: harendrashakya_ # twitter username
  #facebook: facebook_username # facebook username
  #email: your-email@email.com # email adress
  avatar: /assets/img/buddha.webp # change with your own avatar

# URL settings
url: "https://harendra-shakya.github.io/" #
baseurl:
permalink: /:title/
google_analytics: # leave it blank if not wish
fb_appid:

# Collection setting
collections:
  posts:
    output: true
  insights:
    output: true
    # permalink: /insights/:title/
    permalink: /:title/

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 5

# Build settings
# theme: klise
# theme: harendra-shakya.github.io

sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec
  - archive/
  - docs/
  - _insights/up-next/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
